// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma CLI commands like `db pull`/migrations should use a direct DB connection,
    // not the Supabase pooler (PgBouncer).
    url: process.env.DIRECT_URL,
  },
});
